### ISSUE TITLE
Remove MR MIKE on app

### ISSUE THREAD

**Issue by openseatdirect** [cordero67/openseatdirect-in-test#90]
When on the buying page after clicking "Buy Tickets," there reads "powered by MR MIKE" then our OSD logo. Please delete MR MIKE.

https://app.openseatdirect.com/et/mother-s-day-at-iron-peak-55328412723?eventID=55328412723

**Comment by cordero67** [comment]
FIxed and changes in Prod 8/2/23.

**Comment by cordero67** [comment]
Completed.
